import Foundation

// MARK: PasswordlessErrorResponse

/// Model used for the body of error responses.
///
public struct PasswordlessErrorResponse: Decodable {
    /// A URI reference [RFC3986] that identifies the problem type.
    public let type: String

    /// A short, human-readable summary of the problem type.
    public let title: String

    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    public let status: Int

    /// The details of the error.
    public let detail: String?

    /// A URI reference that identifies the specific occurrence of the problem.
    public let instance: String?

    /// An identifier that represents the problem that has occurred.
    public let errorCode: String?
}
